// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductionServiceSystem.Models;

namespace ProductionServiceSystem.Migrations
{
    [DbContext(typeof(CalculatorContext))]
    partial class CalculatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductionServiceSystem.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CostOfWorkingHour")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TransportCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("ProductionServiceSystem.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AssemblyTime")
                        .HasColumnType("float");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Description")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SearchHistoryId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SearchHistoryId");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("ProductionServiceSystem.Models.SearchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ModuleName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleName3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleName4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductionCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.ToTable("SearchHistory");
                });

            modelBuilder.Entity("ProductionServiceSystem.Models.Module", b =>
                {
                    b.HasOne("ProductionServiceSystem.Models.SearchHistory", "SearchHistory")
                        .WithMany()
                        .HasForeignKey("SearchHistoryId");

                    b.Navigation("SearchHistory");
                });

            modelBuilder.Entity("ProductionServiceSystem.Models.SearchHistory", b =>
                {
                    b.HasOne("ProductionServiceSystem.Models.City", null)
                        .WithOne("SearchHistory")
                        .HasForeignKey("ProductionServiceSystem.Models.SearchHistory", "CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductionServiceSystem.Models.City", b =>
                {
                    b.Navigation("SearchHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
